### ISSUE TITLE
Use the crypto API provided by the browsers instead of Math.random

### ISSUE THREAD

**Issue by FSMaxB** [macaullyjames/correcthorsebatterystaple#2]
You can take a look at [this](https://bitbucket.org/jvdl/correcthorsebatterystaple/pull-requests/1/use-uniformly-distributed/diff) for reference.

**Comment by macaullyjames** [comment]
This isn't something that I'm going to invest time in myself but you're more than welcome to send a PR. If you prefer I can add you as a collaborator :)

**Comment by FSMaxB** [comment]
If I find the time, I can do that.

PR is fine. Is also more transparent.

**Comment by macaullyjames** [comment]
Great! 🤓 🎉
